databaseType = "MySql"
id = "e00a889c-e4ca-4310-bac3-a38eaaf681e0"
name = "test_whatsapp"

[environments.target1]
schemas = [ "test_whatsapp" ]
url = "jdbc:mysql://192.168.7.38:3306"

[flyway]
callbackLocations = [ "filesystem:callbacks" ]
locations = [ "filesystem:migrations" ]
mixed = true
outOfOrder = true
schemaModelLocation = "schema-model"
validateMigrationNaming = true

[flywayDesktop]
enableMigrations = true
developmentEnvironment = "development"
shadowEnvironment = "shadow"

  [flywayDesktop.generate]
  undoScripts = false

[redgateCompare]
filterFile = "filter.rgf"

[redgateCompare.mysql.options.ignores]
ignoreNewlinesInTextObjects = "off"
